# Clustering testing

## Clustering before dimensionality reduction

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('../')
import pandas as pd
from src.algorithms.own_kmeans import OK_Means
from src.datapipeline import MLDataset
from pathlib import Path
import numpy as np
data_path = '../data/processed/' 

In [3]:
iris_path = Path('../data/raw/iris.arff')
iris = MLDataset(iris_path)
iris_data = iris.processed_data
iris_X, iris_Y = iris_data.iloc[:,:-1].values, iris_data.iloc[:,-1].values
iris_X.shape, iris_Y.shape

---Preprocessing iris.arff dataset---
Nan values: 0


((150, 4), (150,))

In [4]:
new_var = np.array([[1], [2], [3]])

In [5]:
k_means = OK_Means(new_var)
k_means.data

array([[1],
       [2],
       [3]])

In [6]:
k_means.data = iris_X
k_means.data

array([[-9.00681170e-01,  1.03205722e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00, -1.24957601e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.38535265e+00,  3.37848329e-01, -1.39813811e+00,
        -1.31297673e+00],
       [-1.50652052e+00,  1.06445364e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.02184904e+00,  1.26346019e+00, -1.34127240e+00,
        -1.31297673e+00],
       [-5.37177559e-01,  1.95766909e+00, -1.17067529e+00,
        -1.05003079e+00],
       [-1.50652052e+00,  8.00654259e-01, -1.34127240e+00,
        -1.18150376e+00],
       [-1.02184904e+00,  8.00654259e-01, -1.28440670e+00,
        -1.31297673e+00],
       [-1.74885626e+00, -3.56360566e-01, -1.34127240e+00,
        -1.31297673e+00],
       [-1.14301691e+00,  1.06445364e-01, -1.28440670e+00,
        -1.44444970e+00],
       [-5.37177559e-01,  1.49486315e+00, -1.28440670e+00,
        -1.31297673e+00],
       [-1.26418478e+00,  8.00654259e-01, -1.22754100e+00,
      

In [7]:
settings = {'kmeans': [OK_Means, OK_Means.kmeans]}

In [18]:
#settings['kmeans'][0](iris_X)
settings['kmeans'][0](iris_X).fit(2)

Results(labels=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64), centers=array([[ 0.50728948, -0.4211534 ,  0.65243918,  0.62756431],
       [-1.01457897,  0.84230679, -1.30487835, -1.25512862]]), inertia=223.73200573676343)

In [10]:
OK_Means(iris_X).kmeans_exp(2)

Results(labels=array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64), centers=array([[ 0.50728948, -0.4211534 ,  0.65243918,  0.62756431],
       [-1.01457897,  0.84230679, -1.30487835, -1.25512862]]), inertia=223.73200573676343)

In [32]:
k_means.kmeans_exp(10, 100, 40, True)

-----Attempt 1-----
Iteration 0, Inertia: 114.43865443334018
Iteration 1, Inertia: 78.24776252248469
Iteration 2, Inertia: 67.99690463497471
Iteration 3, Inertia: 62.72088055316598
Iteration 4, Inertia: 60.771945653023906
Iteration 5, Inertia: 59.54310909689625
Iteration 6, Inertia: 58.529813472032885
Iteration 7, Inertia: 58.39776740869942
Iteration 8, Inertia: 58.27323571883073
Iteration 9, Inertia: 57.834601232594224
Iteration 10, Inertia: 57.60411607938073
Converged iteration 11, Inertia: 57.60411607938073
-----Attempt 2-----
Iteration 0, Inertia: 104.1809605633505
Iteration 1, Inertia: 73.01536023579807
Iteration 2, Inertia: 68.61069372307412
Iteration 3, Inertia: 67.62637033976424
Iteration 4, Inertia: 66.60871624873661
Iteration 5, Inertia: 66.28637917078623
Iteration 6, Inertia: 66.21419560528454
Converged iteration 7, Inertia: 66.21419560528454
-----Attempt 3-----
Iteration 0, Inertia: 98.20742396323632
Iteration 1, Inertia: 69.45352036047342
Iteration 2, Inertia: 61.584596498

Results(labels=array([7, 2, 2, 2, 7, 9, 7, 7, 2, 2, 9, 7, 2, 2, 9, 9, 9, 7, 9, 9, 7, 9,
       7, 7, 7, 2, 7, 7, 7, 2, 2, 7, 9, 9, 2, 2, 7, 2, 2, 7, 7, 2, 2, 7,
       9, 2, 9, 2, 9, 7, 4, 4, 4, 0, 4, 8, 4, 0, 4, 0, 0, 8, 0, 8, 8, 4,
       8, 8, 3, 0, 4, 8, 3, 8, 4, 4, 4, 4, 8, 0, 0, 0, 8, 3, 8, 4, 4, 3,
       8, 0, 0, 8, 8, 0, 8, 8, 8, 8, 0, 8, 1, 3, 5, 4, 1, 5, 0, 5, 3, 6,
       1, 3, 1, 3, 3, 1, 4, 6, 5, 3, 1, 3, 5, 3, 1, 5, 3, 4, 3, 5, 5, 6,
       3, 3, 3, 5, 1, 4, 4, 1, 1, 1, 3, 1, 1, 1, 3, 4, 1, 4], dtype=int64), centers=array([[-0.59776149, -1.46378904,  0.00725715, -0.05459259],
       [ 0.94107046,  0.3069946 ,  1.00917669,  1.41289618],
       [-1.38535265, -0.03496756, -1.3381132 , -1.33488889],
       [ 0.35563833, -1.02621125,  0.75976571,  0.77675153],
       [ 0.72066033, -0.01476571,  0.61111677,  0.53390547],
       [ 1.92656914, -0.30493769,  1.42619186,  1.03892863],
       [ 2.12851559,  1.57199748,  1.50201279,  1.360307  ],
       [-0.96445373,  0.89808709, -1

In [14]:
from src.algorithms.agglomerative_sklearn import Agglomerative_sklearn

In [17]:
agg_sk = Agglomerative_sklearn(iris_X)
agg_sk.fit(3)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)